services:
  app:
    build: .
    container_name: fintech-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/fintech
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      - fintech-network

  db:
    image: postgres:15
    container_name: fintech-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: fintech
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - fintech-network

volumes:
  postgres-data:

networks:
  fintech-network:
